production:
  announcements: C0266FRGT
  library: C078Q8PBD4G
  ship: C0M8PUPU6
  welcome: C75M7C0SY
  hq_eng: C05SVRTCDGV
  neighbourhood: C01AS1YEM8A
  lounge: C0266FRGV
  pyramid-scheme: C07N1TCHY3T
  waiting_room: C0A24UHUMA7
shared:
  announcements: C09N763H20Z
  library: C09MMSJSUKV
  ship: C09MS75D9NJ
  welcome: C09MQR23085
  hq_eng: C09N76HCM9P
  neighbourhood: C09MU9EC9GA
  lounge: C09NNJRQGP2
  waiting_room: C09N763H20Z
  identity_help: C092833JXKK
  flavortown_bulletin: C09MATJJZ5J
  flavortown_construction: C09KCFWQSKE
  flavortown_esplanade: C09MPB8NE8H
  flavortown_help: C09MATKQM8C
  happenings: C05B6DBN802
  community: C01D7AHKMPF
  blueprint: C083S537USC
  blueprint_support: C09CMJV6V6K
  blueprint_announcements: C09D1C2BFKL
  campfire_flagship: C0A1GH3FY4T
  campfire_flagship_bulletin: C0A6RKLB4UC
  campfire_flagship_help: C0A6KLGRZQE