production:
  announcements: C0266FRGT
  library: C078Q8PBD4G
  ship: C0M8PUPU6
  welcome: C75M7C0SY
  hq_eng: C05SVRTCDGV
  neighbourhood: C01AS1YEM8A
  lounge: C0266FRGV
  cave: C039PAG1AV7
shared:
  announcements: C09N763H20Z
  library: C09MMSJSUKV
  ship: C09MS75D9NJ
  welcome: C09MQR23085
  hq_eng: C09N76HCM9P
  neighbourhood: C09MU9EC9GA
  lounge: C09NNJRQGP2
  cave: C039PAG1AV7